version: "3"
services:
   adminer:
     image: emilevauge/whoami
     labels:
       - 'traefik.enable=true'
       - 'traefik.backend=whoami'
       - 'traefik.port=9000'
       - 'traefik.frontend.rule=Host:local.whoami.com'
     restart: always
     container_name: whoami
