version: "3.8"
services:
  adminer:
    image: emilevauge/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`local.whoami.com`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    restart: unless-stopped
    container_name: whoami
