version: "3.2"

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 8086:3001
    restart: unless-stopped
    container_name: uptime_kuma
