version: "3"
services:
   traefik:
     image: traefik:v1.7.33-alpine
     environment:
       - "TRAEFIK_API_INSECURE=true"
       - "TRAEFIK_PROVIDERS_DOCKER=true"
       - "TRAEFIK_LOG_LEVEL=INFO"
     command:
       - "--api=true"
       - "--docker=true"
       - "--providers.docker.network=traefik-web"
     volumes:
       - "/var/run/docker.sock:/var/run/docker.sock"
       - "./traefik/traefik.toml:/traefik.toml"
       - "./traefik/acme.json:/acme.json"
     ports:
       - '80:80'
       - '8000:80'
       - '8080:8080' # Dashboard
     labels:
      - 'traefik.backend=traefik'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:local.traefik.com'
     restart: always
     container_name: traefik

networks:
  web:
    external: true
    name: network-web
  backend:
    name: network-backend