# REFERENCE
# https://github.com/linkwarden/linkwarden/blob/main/docker-compose.yml
# https://docs.linkwarden.app/self-hosting/installation

networks:
  linkwarden:
    name: linkwarden

volumes:
  aplication-data:
    name: linkwarden-data
  database-data:
    name: linkwarden-database

services:
  linkwarden:
    container_name: linkwarden-web
    image: ghcr.io/linkwarden/linkwarden:v2.5.3
    restart: unless-stopped
    depends_on:
      - database
    networks:
      - linkwarden
    ports:
      - ${PORT_LINKWARDEN:-5173}:3000
    volumes:
      - aplication-data:/data/data
      - ./logs:/logs
    env_file: .env

  database:
    container_name: linkwarden-database
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - linkwarden
    ports:
      - ${PORT_POSTGRES:-8090}:5432
    volumes:
      - database-data:/var/lib/postgresql/data
      - ./logs:/logs
    env_file: .env
