networks:
  penpot:
    name: penpot

volumes:
  database-data:
    name: penpot-database
  assets:
    name: penpot-assets

services:
  penpot-frontend:
    image: "penpotapp/frontend:2.0.3"
    container_name: penpot-frontend
    env_file: .env
    depends_on:
      - penpot-backend
      - penpot-exporter
    networks:
      - penpot
    volumes:
      - assets:/opt/data
    ports:
      - ${PENPOT_PORT_FRONTEND:-5020}:80

  penpot-backend:
    image: "penpotapp/backend:2.0.3"
    container_name: penpot-backend
    env_file: .env
    depends_on:
      - penpot-postgres
      - penpot-redis
    networks:
      - penpot
    volumes:
      - assets:/opt/data

  penpot-exporter:
    image: "penpotapp/exporter:2.0.3"
    container_name: penpot-exporter
    networks:
      - penpot

  penpot-postgres:
    image: "postgres:15"
    container_name: penpot-database
    restart: unless-stopped
    stop_signal: SIGINT
    env_file: .env
    networks:
      - penpot
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - ${PENPOT_PORT_POSTGRES:-5432}:5432
    environment:
      - POSTGRES_INITDB_ARGS=--data-checksums

  penpot-redis:
    image: redis:7
    container_name: penpot-redis
    restart: unless-stopped
    env_file: .env
    networks:
      - penpot

  penpot-mailcatch:
    image: sj26/mailcatcher:latest
    container_name: penpot-mailcatch
    restart: always
    env_file: .env
    networks:
      - penpot
    ports:
      - ${PENPOT_PORT_MAIL:-5021}:1080
    expose:
      - 1025:1025
