# set the base image to Debian
# https://hub.docker.com/_/debian/
FROM debian:11

# replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# update the repository sources list
# and install dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y curl git manpages-dev vim wget && \
    apt-get -y autoclean

# install c++
RUN apt-get install -y ccache build-essential

# install cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.15.2/cmake-3.15.2.tar.gz && \
    tar -zxvf cmake-3.15.2.tar.gz && \
    cd cmake-3.15.2 && \
    ./bootstrap && \
    make && \
    make install

# confirm installation
RUN gcc --version
RUN make --version
RUN cmake --version

# WORKDIR
WORKDIR playground

