version: '3.2'

# MySql has problems using volumes
# volumes:
#   db:

networks:
  net:

services:
  mysql: # <- server name
    image: mysql:8.0.29
    # Without CAP_SYS_NICE enabled, MySQL won't be able to handle thread priorities, and 
    # I guess you will then loose a new feature introduced with MySQL 8 (Resource Groups)
    # https://stackoverflow.com/a/55706057/10369378
    # cap_add:
    #   - SYS_NICE
    environment:
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: mysql
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./var/logs/mysql:/var/log/mysql/
    networks:
      - net # <- mysql_net
    restart: unless-stopped
    container_name: mysql # <- server name (has precedence)