# REFERENCE
# https://tldraw.dev/installation

networks:
  tldraw:
    name: tldraw

services:
  tldraw:
    container_name: tldraw
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - tldraw
    ports:
      - ${TLDRAW_PORT:-3000}:3000
    env_file: .env
