version: "3.2"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    image: pihole/pihole:latest
    environment:
      TZ: 'America/Panama'
      WEBPASSWORD: 'piholerocks'
    ports:
      # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
      # Otherwise, change the ip binding to the correct ip
      - "192.168.0.1:53:53/tcp" # DNS
      - "192.168.0.1:53:53/udp" # DNS
      - "192.168.0.1:67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'    
    cap_add:
      # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
      - NET_ADMIN # Recommended but not required (DHCP needs NET_ADMIN)      
    restart: unless-stopped
    container_name: pihole
