# REFERENCE
# https://github.com/excalidraw/excalidraw/blob/master/docker-compose.yml
# https://docs.excalidraw.com/docs/introduction/development#self-hosting

services:
  excalidraw:
    image: excalidraw/excalidraw:sha-4bfc5bb
    container_name: excalidraw
    restart: unless-stopped
    env_file:
      - path: ".env"
        required: false
      - path: ".env.override"
        required: false
    ports:
      - ${PORT_EXCALIDRAW:-5000}:80
    environment:
      - NODE_ENV=development
