version: "3.2"

networks:
  proxy:
    # ipv4_address: 192.168.1.63
    # https://stackoverflow.com/questions/59069029/how-to-translate-bridge-networks-in-docker-compose-v-3-7
    # https://github.com/htpcBeginner/docker-traefik/blob/master/docker-compose-t2.yml

services:
  traefik:
    image: traefik:v2.5.4
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      #- "--providers.docker.endpoint=tcp://192.168.1.63:80"
      - "--entrypoints.web.address=:80"
      - "--pilot.token=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      #- "./traefik/traefik.toml:/traefik.toml"
      #- "./traefik/acme.json:/acme.json"
    ports:
      - '80:80'
      - '8080:8080' # Dashboard
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`local.traefik.com`)"
      - "traefik.http.routers.traefik.entrypoints=proxy"
      - "traefik.http.routers.traefik.service=traefikservice"
      - "traefik.http.services.traefikservice.loadbalancer.server.port=9080"
      - "traefik.http.services.traefikservice.loadbalancer.server.scheme=http"  
      - "traefik.docker.network=proxy"
    restart: unless-stopped
    container_name: traefik
