version: '3.8'
services:
  bin-nodejs:
    image: bin-nodejs
    entrypoint: ["tail", "-f", "/dev/null"]
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./binaries:/node_versions
      - ./playground:/playground
    restart: unless-stopped
    container_name: bin_nodejs


