version: '3.8'

services:
  bin-nodejs:
    image: bin-nodejs
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./binaries:/node_versions
      - ./playground:/playground
    restart: always
    entrypoint: ["tail", "-f", "/dev/null"]
    container_name: bin_nodejs


