version: "3"

networks:
  proxy:

services:
  adminer:
    image: adminer:4.8.1-standalone
    environment:
      ADMINER_AUTOLOGIN: 1
      ADMINER_NAME: Sinispa
      ADMINER_SALT: adminer-salt
      # Drivers
        # MySQL         | server
        # SQLite 3      | sqlite
        # SQLite 2      | sqlite2
        # PostgreSQL    | pgsql
        # Oracle        | oracle
        # MS SQL        | mssql
        # Firebird      | firebird
        # SimpleDB      | simpledb
        # MongoDB       | mongo
        # Elasticsearch | elastic
      ADMINER_DRIVER: server
      ADMINER_SERVER: adminer_mysql
      ADMINER_USERNAME: adminer
      ADMINER_PASSWORD: adminer
      ADMINER_DB: adminer
      # ADMINER_DEFAULT_SERVER: adminer-mysql
      # ADMINER_DEFAULT_USERNAME: adminer
      # ADMINER_DEFAULT_PASSWORD: adminer
      # ADMINER_DEFAULT_DATABASE: adminer
    ports:
      - 9080:8080
    networks:
       - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`local.adminer.com`)"
      - "traefik.http.routers.adminer.entrypoints=proxy"
      - "traefik.http.routers.adminer.service=adminerservice"
      - "traefik.http.services.adminerservice.loadbalancer.server.port=9080"
      - "traefik.http.services.adminerservice.loadbalancer.server.scheme=http"  
      - "traefik.docker.network=proxy"
    restart: unless-stopped
    container_name: adminer
