version: "3"

networks:
  proxy:

services:
  adminer:
    image: wodby/adminer:4.3-1.1.0
    environment:
      ADMINER_SALT: adminer-salt
    ports:
      - 9080:8080
    networks:
       - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`local.adminer.com`)"
      - "traefik.http.routers.adminer.entrypoints=proxy"
      - "traefik.http.routers.adminer.service=adminerservice"
      - "traefik.http.services.adminerservice.loadbalancer.server.port=9080"
      - "traefik.http.services.adminerservice.loadbalancer.server.scheme=http"  
      - "traefik.docker.network=proxy"
    restart: unless-stopped
    container_name: adminer
