version: '3.8'
services:
  svc-nginx:
    image: wyveo/nginx-php-fpm:php74
    volumes:
      - ./web:/usr/share/nginx/html
      - ./var/logs/nginx:/var/log/nginx
    ports:
      - 85:80
    restart: unless-stopped
    container_name: svc_nginx
