version: "3.8"
services:
  aria2-pro:
    image: p3terx/aria2-pro
    # If you use host network mode, then no port mapping is required.
    # This is the easiest way to use IPv6 networks.
    #    network_mode: host
    network_mode: bridge
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=IARDO
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=CUSTOM_TRACKER_URL
      - CUSTOM_TRACKER_URL=
      - TZ=PA
    volumes:
      - ${PWD}/aria2-config:/config
      - ~/Downloads/Management/Aria2:/downloads
    ports:
      - 6800:6800
      - 6888:6888
      - 6888:6888/udp
    # Since Aria2 will continue to generate logs, limit the log size to 1M to prevent your hard disk from running out of space.
    logging:
      driver: json-file
      options:
        max-size: 1m
    restart: unless-stopped
    container_name: aria2_pro

  # AriaNg is just a static web page, usually you only need to deploy on a single host.
  ariang:
    image: p3terx/ariang
    command: --port 6880 --ipv6
    # network_mode: host
    network_mode: bridge
    ports:
      - 6880:6880
    logging:
      driver: json-file
      options:
        max-size: 1m
    restart: unless-stopped
    container_name: aria2_pro_ng
