version: '3.2'
services:
  bin-python:
    image: bin-python
    entrypoint: ["tail", "-f", "/dev/null"]
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./binaries:/python_versions
      - ./playground:/playground
    restart: unless-stopped
    container_name: bin_python


