version: '3.2'

volumes:
   firefly3_upload:
   firefly3_db:

services:
  firefly3-web:
    image: fireflyiii/core:latest
    env_file: .env
    volumes:
      - firefly3_upload:/var/www/html/storage/upload
    ports:
      - 80:8080
    depends_on:
      - firefly3-db
    restart: unless-stopped
    container_name: firefly3_web

  firefly3-db:
    image: mariadb    
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=secret_firefly_password
      - MYSQL_DATABASE=firefly
    volumes:
      - firefly3_db:/var/lib/mysql
    restart: unless-stopped
    container_name: firefly3_db
