version: '3.2'
services:
  bin-php:
    image: bin-php
    entrypoint: ["tail", "-f", "/dev/null"]
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./playground:/playground
    restart: unless-stopped
    container_name: bin_php


