# set the base image to Debian
# https://hub.docker.com/_/debian/
FROM debian:11

# replace shell with bash so we can source files
RUN rm /bin/sh && ln -s /bin/bash /bin/sh

# update the repository sources list
# and install dependencies
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y curl wget vim && \
    apt-get -y autoclean

# add SURY repository
RUN apt-get install -y lsb-release apt-transport-https ca-certificates && \
    wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg && \
    echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/php.list && \
    apt-get update

# install php
RUN apt-get install -y php5.6-{cli,xdebug,xml,zip} && \
    apt-get install -y php7.0-{cli,xdebug,xml,zip} && \
    apt-get install -y php7.1-{cli,xdebug,xml,zip} && \
    apt-get install -y php7.2-{cli,xdebug,xml,zip} && \
    apt-get install -y php7.3-{cli,xdebug,xml,zip} && \
    apt-get install -y php7.4-{cli,xdebug,xml,zip} && \
    apt-get install -y php8.0-{cli,xdebug,xml,zip}

# set default php version
RUN update-alternatives --set php /usr/bin/php8.0

# confirm installation
RUN php -v
RUN php -m | grep xdebug


