version: '3.8'

services:
  bin-nodejs:
    image: bin-cplusplus
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./playground:/playground
    entrypoint: ["tail", "-f", "/dev/null"]
    container_name: bin_cplusplus

