version: '3.2'
services:
  bin-cplusplus:
    image: bin-cplusplus
    entrypoint: ["tail", "-f", "/dev/null"]
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./playground:/playground
    container_name: bin_cplusplus

