version: '3.8'

volumes:
  db:

networks:
  net:

services:
  postgres: # <- server name
    image: postgres
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
      - ./logs/postgres:/var/log/postgresql
    networks:
      - net # <- postgres_net
    restart: unless-stopped
    container_name: postgres # <- server name (has precedence)