version: "3.7"

networks:
  backend:
    name: openproject-backend
    external: true

volumes:
  pgupgrade:
    name: openproject-pgupgrade
  pgdata:
    name: openproject-pgdata
    external: true
  opdata:
    name: openproject-opdata
    external: true
  assets:
    name: openproject-assets
    external: true

services:
  backup:
    container_name: openproject-backup
    entrypoint: ["tail", "-f", "/dev/null"]
    restart: "no"
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - "./backups:/backups"
      - "./:/control"
      - "${PGDATA:-pgdata}:/var/lib/postgresql/data"
      - "${OPDATA:-opdata}:/var/openproject/assets"
    networks:
      - backend
    environment:
      PGDATA: /var/lib/postgresql/data
      OPDATA: /var/openproject/assets
  upgrade:
    container_name: openproject-upgrade
    entrypoint: ["tail", "-f", "/dev/null"]
    restart: "no"
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - "./:/control"
      - "${PGDATA:-pgdata}:/var/lib/postgresql/data"
    networks:
      - backend
    environment:
      PGDATA: /var/lib/postgresql/data
