version: "3.7"

volumes:
  pgupgrade:
    name: openproject-pgupgrade
  pgdata:
    name: openproject-pgdata
  opdata:
    name: openproject-opdata
  assets:
    name: openproject-assets

services:
  backup:
    container_name: openproject-backup
    entrypoint: ["/control/backup-entrypoint.sh"]
    restart: "no"
    build:
      context: .
      dockerfile: dockerfile
    environment:
      PGDATA: /var/lib/postgresql/data
      OPDATA: /var/openproject/assets
    volumes:
      - "./backups:/backups"
      - "./:/control"
      - "${PGDATA:-pgdata}:/var/lib/postgresql/data"
      - "${OPDATA:-opdata}:/var/openproject/assets"
  upgrade:
    container_name: openproject-upgrade
    entrypoint: ["/control/upgrade-entrypoint.sh"]
    restart: "no"
    build:
      context: .
      dockerfile: dockerfile
    environment:
      PGDATA: /var/lib/postgresql/data
    volumes:
      - "./:/control"
      - "${PGDATA:-pgdata}:/var/lib/postgresql/data"
