version: "3.7"

networks:
  backend:
    name: openproject-backend
    external: true

volumes:
  pgupgrade:
    name: openproject-pgupgrade
  pgdata:
    name: openproject-pgdata
    external: true
  opdata:
    name: openproject-opdata
    external: true
  assets:
    name: openproject-assets
    external: true

services:
  backup:
    container_name: openproject-backup
    entrypoint: ["tail", "-f", "/dev/null"]
    restart: "no"
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./backups:/backups
      - ./:/control
      - pgdata:/var/lib/postgresql/data
      - opdata:/var/openproject/assets
      - assets:/app/public
    networks:
      - backend
  upgrade:
    container_name: openproject-upgrade
    entrypoint: ["tail", "-f", "/dev/null"]
    restart: "no"
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./:/control
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
