version: "3.2"

services:
  epicstore-claimer:
    image: ghcr.io/jackblk/epicgames-freebies-claimer:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - ./data:/app/data
    ports:
      - 8765:80
    restart: unless-stopped
    container_name: epicstore_claimer
